---
title: "Plans & Pricing"
linkTitle: "Pricing"
weight: 25
wide-page: true
noDonateBanner: true
---

*LibrePCB is free & open-source software and we commit to keep it that way*. +
Optionally you can support the project and unlock *additional benefits* with
a subscription plan.

++++
<div class="pricing-table">
  <div class="pricing-row">
    <div class="pricing-col feature-col">
      <div class="feature-card">
        <div class="card-header">
          <div>&nbsp;</div>
          <div class="fs-6 text-muted">&nbsp;</div>
          <div class="text-muted fw-lighter card-price-annual">&nbsp;</div>
        </div>
        <div class="card-body">
          <ul>
            <li>Fully Open-Source Application</li>
            <li>For Personal &amp; Commercial Use</li>
            <li>No Limitations in Offline Features</li>
            <li>Get Our Official Libraries (Online)<sup>2</sup></li>
            <li>Join Private Chats (Support/Dev)<sup>3</sup></li>
            <li>Get Proprietary 3D Models (Online)<sup>2,4</sup></li>
            <li>Import Parts On-Demand (Online)<sup>2,4</sup></li>
            <li>Import From Datasheets (Online)<sup>2,4</sup></li>
            <li>Live Parts Information (Online)<sup>2,4</sup></li>
            <li>Autorouter (Online)<sup>2,4</sup></li>
            <li>Feature Request &amp; Bugfix Priority<sup>5</sup></li>
            <li>Personal Support (Chat/E-Mail/Phone)<sup>6</sup></li>
            <li>Multi-User License Management<sup>7</sup></li>
            <li></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="pricing-col">
      <div class="pricing-card card-free">
        <div class="card-header position-relative">
          <div>FREE</div>
          <div class="fs-6 text-muted">0€ / month</div>
          <div class="text-muted fw-lighter card-price-annual">no strings attached</div>
        </div>
        <div class="card-body">
          <ul>
            <li class="check-icon"></li>
            <li class="check-icon"></li>
            <li class="check-icon"></li>
            <li class="check-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li><a href="{{< relref "download/index.adoc" >}}" class="btn btn-primary btn-pricing" role="button">Download</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="pricing-col">
      <div class="pricing-card card-standard">
        <div class="card-header position-relative">
          <div>Maker</div>
          <div class="fs-6 text-muted">4€ / month<sup>*</sup></div>
          <div class="text-muted fw-lighter card-price-annual">or 40€ / year<sup>*</sup></div>
          <span class="position-absolute top-0 translate-middle badge rounded-pill bg-warning pricing-badge">
            includes<br/>4€/month<br/>credit!<sup>1</sup>
          </span>
        </div>
        <div class="card-body">
          <ul>
            <li class="check-icon"></li>
            <li class="check-icon"></li>
            <li class="check-icon"></li>
            <li><span class="check-icon"></span></li>
            <li><span class="check-icon"></span></li>
            <li><span class="warn-icon"></span> 20 / month</li>
            <li><span class="warn-icon"></span> 20 / month</li>
            <li><span class="warn-icon"></span> 20 / month</li>
            <li><span class="warn-icon"></span> 50 / day</li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li class="cross-icon"></li>
            <li><a href="#" class="btn btn-warning btn-pricing" role="button">Subscribe</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="pricing-col">
      <div class="pricing-card card-professional">
        <div class="card-header position-relative">
          <div>Professional</div>
          <div class="fs-6 text-muted">10€ / month<sup>*</sup></div>
          <div class="text-muted fw-lighter card-price-annual">or 100€ / year<sup>*</sup></div>
          <span class="position-absolute top-0 translate-middle badge rounded-pill bg-warning pricing-badge">
            includes<br/>10€/month<br/>credit!<sup>1</sup>
          </span>
        </div>
        <div class="card-body">
          <ul>
            <li class="check-icon"></li>
            <li class="check-icon"></li>
            <li class="check-icon"></li>
            <li><span class="check-icon"></span></li>
            <li><span class="check-icon"></span></li>
            <li><span class="check-icon"></span> 200 / month</li>
            <li><span class="check-icon"></span> 200 / month</li>
            <li><span class="check-icon"></span> 200 / month</li>
            <li><span class="check-icon"></span> 300 / day</li>
            <li><span class="check-icon"></span></li>
            <li><span class="check-icon"></span></li>
            <li><span class="check-icon"></span> From Project Lead (EN/DE)</li>
            <li class="cross-icon"></li>
            <li><a href="#" class="btn btn-warning btn-pricing" role="button">Subscribe</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="pricing-col">
      <div class="pricing-card card-enterprise">
        <div class="card-header">
          <div>Enterprise</div>
          <div class="fs-6 text-muted">59€ / month / user<sup>*</sup></div>
          <div class="text-muted fw-lighter card-price-annual">or 590€ / year / user<sup>*</sup></div>
        </div>
        <div class="card-body">
          <ul>
            <li class="check-icon"></li>
            <li class="check-icon"></li>
            <li class="check-icon"></li>
            <li><span class="check-icon"></span></li>
            <li><span class="check-icon"></span></li>
            <li><span class="check-icon"></span> 200 / month / user</li>
            <li><span class="check-icon"></span> 200 / month / user</li>
            <li><span class="check-icon"></span> 200 / month / user</li>
            <li><span class="check-icon"></span> 300 / day / user</li>
            <li><span class="check-icon"></span></li>
            <li><span class="check-icon"></span></li>
            <li><span class="check-icon"></span> From Project Lead (EN/DE)</li>
            <li><span class="check-icon"></span></li>
            <li><a href="#" class="btn btn-warning btn-pricing disabled" role="button">Coming Soon</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <p class="mt-2 text-end small text-muted"><sup>*</sup>All prices excl. VAT</p>
</div>
++++

.Notes & Terms (please read before subscribing)
[%collapsible]
====
[.sponsor-tier-details]
^1^ With these subscriptions you will get a monthly credit at our manufacturing
partner https://aisler.net[AISLER] for PCB orders made through
https://fab.librepcb.org[LibrePCB Fab], with the same amount as the LibrePCB
subscription costs -- so if you order PCBs every month for at least this amount,
the complete LibrePCB subscription is for free! Note that unused credits do
not sum up to the next month, i.e. credits expire after a month.

[.sponsor-tier-details]
^2^ Those features rely on online services and/or external partners. We do our
best to keep the uptime close to 100% but there is *no guarantee* for those
to operate properly. In rare cases there might be short downtimes or in
worst case even long downtimes or permanent service shutdown if the problem
is not under our control. There is no right for a refund in case of downtime.

[.sponsor-tier-details]
^3^ You get access to private chats which allow to put questions with a high
probability that a project member will answer. Please respect a *fair use* of
these chats (do not spam with lots of trivial questions). There is no right
to get answers (real personal support is only included in the higher tiers).
To get access to these chats, you need a Matrix account. We have chosen this
open-source solution for transparency & privacy reasons.

[.sponsor-tier-details]
^4^ Those features come with a certain usage limit. The Maker subscription is
intended for occasional, simple, small projects. The higher subscriptions
are intended for professional work on more complex projects as a daily
business. Each feature has its own rate limit. Once exceeded, the particalar
feature is disabled for the rest of the period (day or month). Unused
contingents do not sum up to the following period, i.e. they expire.

[.sponsor-tier-details]
^5^ Usually a response is provided within 24 hours but in rare cases it may
take up to 3 business days. The personal support is given on a *fair use*
basis. For real problems and serious questions the project lead will help
with best effort and high motivation. But in case of excessive consultation
for trivial questions, the project lead reserves the right to ask for a
dedicated payment before spending more time on personal support. For Enterprise
subscribers we kindly ask you to collect any support requests and contact us
through a single representative rather than every user individually.

[.sponsor-tier-details]
^6^ Please note that there is *no guarantee* for any reported issues or
feature requests to be resolved. We guarantee to seriously consider every
request so we will hear your voice for sure. If reasonable, we may even
provide nightly builds resolving those requests. But in the end we always
act with our long-term vision and goals in mind, so not every feature
request may be implemented.

[.sponsor-tier-details]
^7^ The Enterprise tier is purchased and managed by a single person, i.e. only
one email address & credit card is required. You then get access to a user
management interface which allows you to grant or revoke access to your
LibrePCB license for every user individually. The indicated price of this
tier is automatically multiplied with the number of active users so only
one payment is done for all active users together.
====

---

== icon:circle-question[] Frequently Asked Questions

{empty}

.What payment methods are supported?
[%collapsible]
====
Currently we support credit cards. More options will be provided in future.
====

.How many users can use a subscription?
[%collapsible]
====
The Maker & Professional subscriptions are valid only for a single user.
For example if 5 users will work with LibrePCB, you need to buy 5 individual
subscriptions. Only the Enterprise subscription is valid for any number of
users and comes with a user management interface.
====

.Can we buy a subscription for multiple users?
[%collapsible]
====
It's not possible yet to buy a subscription for multiple users, this is on
the roadmap. Currently you have to buy a separate subscription for each user,
which is possible with a single account (i.e. use the same e-mail address
for each purchase).
====

.Can I install LibrePCB on multiple devices?
[%collapsible]
====
Yes. A subscription is bound to a user. If a user has installed LibrePCB on
multiple devices, only one subscription is required. But if multiple users
work with LibrePCB, you need a separate subscription for each user.
====

.I'm rarely using LibrePCB / I don't like subscriptions, can I make a one-time purchase?
[%collapsible]
====
Since the major benefits of our subscriptions are server-side services and
support services, we can't offer those for a one-time payment. If you just
want to use LibrePCB for a few days to get a project done, feel free to
start a monthly subscription and immediately cancel it afterwards. This
way you are charged only one monthly rate and the subscription stays valid
until the end of the subscription period.
====

.Is there any volume discount?
[%collapsible]
====
For up to 10 users there is no volume discount. For Enterprise subscriptions
with more than 10 users, please
link:{{< relref "about/contact/index.adoc" >}}[contact us].
====

.Do you offer a discount for non-profits, schools, OSHW projects etc.?
[%collapsible]
====
In some cases we may provide a discount, please
link:{{< relref "about/contact/index.adoc" >}}[contact us] and we will consider
every case individually. But a discount may only be offered if the following
requirements are met:

* You are using LibrePCB mainly for educational, non-commercial or open-source
  hardware projects
* You have a reasonable publicity, for example students in your school will use
  LibrePCB, or you are building hardware which have a big public visibility
* You put the "Made With LibrePCB" logo on all your schematics & PCBs
====

.With a subscription, will you implement the features & bugfixes which I need?
[%collapsible]
====
The higher level subscriptions allow you to vote for features or other tasks
to give them a higher priority. However, there is no guarantee we will work
on these tasks soon as we always have to make decisions based on the whole
community instead of a few individual users.

If you really need a particular feature, bugfix, custom integration into your
IT landscape, missing library elements etc, please
link:{{< relref "about/contact/index.adoc" >}}[contact us]. We will check if
it is a doable task in which case we would make you an offer to fund that
particular task.
====

.I have privacy concerns/questions!
[%collapsible]
====
Then you are in good company :-) We really care about privacy and want to
be transparent about it. Here some details:

* Without a subscription, you can use LibrePCB for free and completely without
  any account. We won't ask you for an email address, name, credit card or
  whatever. Just download the application and run it, period.
* With a subscription, there is no anonymous payment method yet but we ask
  only for the absolutely necessary information -- that is an email address,
  credit card details, and the country/state you live in (required to
  determine VAT).
* We use https://polar.sh[Polar] as our Merchant of Record, that means they
  are responsible for payment & billing so they show up as merchant on the
  credit card bill. We searched hard to find a payment provider which does
  not require us to sell our souls -- and luckily found Polar, which is not
  even developer-friendly & privacy-respecting, but even open-source software!
  Please check out their website for details about their privacy policy etc.
* We neither process nor store your credit card details. Everything is handled
  by Polar, which in turn uses Stripe to process and store credit card details.
  Those sensitive information is never going through our servers so we won't
  even see them.

If you still have any concerns or questions, please don't hesitate to
link:{{< relref "about/contact/index.adoc" >}}[contact us].
====
