---
date: 2026-01-13
title: LibrePCB 2.0.0 RC1 Released
author: U. Bruhin
preview: new-window.png
---

I'm very excited to announce that LibrePCB 2.0 is feature-complete and that
a first release candidate is available for download!

<!--more-->

About This Release Candidate
----------------------------

LibrePCB 2.0 contains a huge amount of changes compared to the previous
release. Even though we give our best to keep the quality high and do lots
of testing, such large changes always come with the risk of bugs. Thus, we
first provide a release candidate prior to the official stable release.

Note that while we do not expect that any serious problems occur with your
projects when using this release candidate, it's still a good idea to create
a backup first (e.g. by using a version control system).

If you experience any issues with this release candidate, please
link:{{< relref "help/help/index.adoc" >}}[let us know] (e.g. a quick
notification in our Matrix chat) so we can fix them in the final release!
A list of known limitations / issues is available
https://github.com/LibrePCB/LibrePCB/issues/1655[here].

[TIP]
====
When you open a LibrePCB 1.x workspace the first time with LibrePCB 2.x, all
libraries will be migrated to the new file format in the background library
scan. Therefore it is expected that the first scan takes much more time than
usual.
====

Major Changes
-------------

The most exciting change of LibrePCB 2.0 is of course the completely new,
tabbed, split-view, single-window user interface
(https://github.com/LibrePCB/LibrePCB/issues/1494[#1494]) as introduced in
link:{{< relref "blog/2025-09-12_preview_of_next_gen_ui/index.adoc" >}}[this blog post]:

[.imageblock.rounded-window.window-border]
{{< imglink "new window" "new-window.png" >}}

But of course this release comes with many more new features and improvements.
A full changelog and some impressions will be provided in the final release
announcement, so here's just a short list of the most interesting new features
(check out the links to the pull requests for more details):

- Add support for schematic buses
  (https://github.com/LibrePCB/LibrePCB/pull/1646[#1646])
- Support adding images to symbols & schematics
  (https://github.com/LibrePCB/LibrePCB/pull/1578[#1578])
- Support adding individual pads directly to boards
  (https://github.com/LibrePCB/LibrePCB/pull/1596[#1596])
- Support automatic via drill & annular rings from design rules
  (https://github.com/LibrePCB/LibrePCB/pull/1606[#1606],
  https://github.com/LibrePCB/LibrePCB/pull/1611[#1611])
- Support sharing DRC settings & output jobs through libraries
  (https://github.com/LibrePCB/LibrePCB/pull/1631[#1631])
- Signed Windows releases & compatibility with macOS 10.14
  (https://github.com/LibrePCB/LibrePCB/pull/1604[#1604],
  https://github.com/LibrePCB/LibrePCB/pull/1557[#1557])
- And many more!

Next Steps
----------

We expect the final release to be available soon, probably around the
end of January. Meanwhile, we will work on migrating our official
libraries to the new file format, extending our fabrication service to
support LibrePCB 2.x projects, and updating the documentation accordingly.

---

Credits
-------

[.right.ms-3]
{{< imglink "NGI0" "nlnet-ngi0.png" "https://nlnet.nl/project/LibrePCB2.0/" 130 >}}

This release was part of the
link:{{< relref "blog/2024-10-17_roadmap_2.0/index.adoc" >}}[NGI0 Commons grant]
we receive from link:https://nlnet.nl[NLnet], which was a huge help for us
to get this work done. We are very thankful for their support.

Starting with this release, our executables for Windows are signed by
https://ossign.org/[OSSign], thanks a lot for their sponsored code-signing.

Also a big thank you to our link:{{< relref "sponsors/sponsors/index.adoc" >}}[sponsors]
and to the community helping us with translations, pull requests, donations
and other contributions! 🎉

---

Download
--------

Since this is not a stable release yet, use the download links *from the
sidebar* on our link:{{< relref "download/index.adoc" >}}[download page].

If you like LibrePCB, please consider making a small
link:{{< relref "donate/index.adoc" >}}[donation] to support the
ongoing development. +
Thank you! icon:heart[]
