---
date: 2025-08-30
title: Preview of LibrePCB 2.0 UI
author: U. Bruhin
---

I've made a lot of progress with the new user interface for LibrePCB 2.0 and
am very excited to share some insights how it will look, and how it makes
LibrePCB better in many ways.

The Original Problem
--------------------

First, let's quickly look back how everything began. Since the early days of
LibrePCB around 2013, we are using Qt as the UI toolkit and the concept was
to implement every editor as a separate window (schematic editor, board editor,
library editor etc.):

[.imageblock]
{{< imglink "old windows" "old-windows.png" >}}

But more features added over time, the UI got more and more crowded. Also
the paradigm of separate windows is often cumbersome to work with -- e.g.
having just one library and one project opened required to constantly switch
between four(!) windows. Even a dual-monitor setup was not enough to work
efficiently with LibrePCB. So it was clear we need a completely new
organization of windows and editors. However, with the traditional approach
that Qt follows, it is really hard to pursue more modern UI paradigms, not
to mention the effort and the error-proneness it involves.

Slint: A Declarative UI Language
--------------------------------

In the blog post
link:{{< relref "blog/2024-10-17_roadmap_2.0/index.adoc" >}}[NGI0 Grant for LibrePCB 2.0]
I listed a few possible solutions how to build a more modern user interface. The
most promising option was https://slint.dev/[Slint], a relatively new UI
toolkit (written in Rust) which uses a custom, declarative language to describe
the UI. Declarative means that relations and behavior can be described in the
language:

{{< highlight qml >}}
Window {
    Button {
        x: parent.width - self.width - 5px;
        y: 5px;
        text: @tr("Open Project");
    }
}
{{< /highlight >}}

It may sound trivial to place a button in the top right edge of its parent,
but with the procedural approach of Qt this is not trivially doable. In many
cases, it requires to implement event handlers in C++ which update the
widgets position whenever the parent object's size or the widgets's own size
has changed. Writing such code is time-consuming and error-prone, while the
declarative approach of Slint is very quick, easy and safe. Now consider this
advantage for a large project like LibrePCB, that contains hundrets or even
thousands of UI elements -- here the declarative approach is really a
game-changer!

An Incremental Migration
------------------------

Unfortunately, even with several months of full-time work, LibrePCB is too
big to be migrated to Slint by 100% at once -- to avoid delaying the next
release too much, we need to do the migration in steps. All the main windows &
editors first, and the remaining dialogs and wizards in later releases. Also
our whole business logic depends on Qt (it is much more than just a UI
framework) so the dependency on Qt will remain for a long time.

So the question is, can we mix Qt with Slint? In the end, LibrePCB only works
if the main thread is running Qt's event loop. But Slint only works when the
main thread is running their event loop. So at first glance it seems we
have a very bad conflict here :-/

In fact, Slint supports
https://docs.slint.dev/latest/docs/slint/guide/backends-and-renderers/backends_and_renderers/[different backends]
for interaction with the underlying system, e.g. for input events handling
and window drawing. These are Qt, https://docs.rs/winit/latest/winit/[winit]
and LinuxKMS. Winit comes with the ability of GPU-accelerated rendering,
which would be interesting for performance reasons. But unfortunately we
can't use winit because of the event loop conflict.

Luckily Slint's Qt backend avoids that problem since Slint will run Qt's
event loop for us. So the event loop will process the events for both, the
Slint UI and the LibrePCB backend. This works because Slint and LibrePCB
are compiled and linked against the same Qt library. It also allows us to
mix the new Slint window with legacy Qt dialogs & wizards, so we can do
a step-by-step migration.

One Window For Everything
-------------------------

Enough background information for now, let's have a look at the new UI of
LibrePCB 2.0. The most important thing is that all the separate windows
mentioned above have been replaced by a single, multifunctional window.
Within that window, any kind of "document" (e.g. a footprint, a schematic or
a board) is opened as a tab. The toolbars therefore now depend on which tab
is currently active -- since for example the footprint editor provides
other tools than the schematic editor, the toolbars of the new window now
depend on the currently active tab. This is how the new window currently
looks like:

[.imageblock]
{{< imglink "new window" "new-window.png" >}}

By the way, in this new window you can now have multiple projects opened at
the same time!

Sidebar & Panel
~~~~~~~~~~~~~~~

A lot of functionality is available from the sidebar. Depending on context,
there are different kinds of panels available. For example if you're working
on a schematic, there is a panel with displays ERC messages. But if you're
working on a board, that panel will display DRC messages.

[.imageblock]
{{< imglink "side panels" "side-panels.png" >}}

The sidebar shows you status information about various parts of the
application. For example you see if there are ERC warnings or outdated
workspace libraries without even opening the corresponding panel:

[.imageblock]
{{< imglink "side buttons" "side-buttons.png" >}}

Working Area
~~~~~~~~~~~~

The most important part of our UI is of course the working area where you
draw schematics, layout traces etc. This area has been improved in many ways.
Not only that _everything_ is now a tab (remember that schematics were not
tabs in the old UI), you can now even split the window into multiple sections
and open tabs side-by-side. For example if you're working on a single-monitor
setup, it is now easy to work on the board while still having the schematics
in sight:

[.imageblock]
{{< imglink "split section" "split-section.png" >}}

In addition, the working area has been maximized and decluttered to have as
much of the screen size available for the graphics view as possible. For
example, tool buttons are now overlays inside the editors rather than global,
old-school toolbars spanning the whole window height or width even though
only a third of it is filled with buttons.

Statusbar & Notifications
~~~~~~~~~~~~~~~~~~~~~~~~~

We already had a status bar in the old UI, but it was purely visual and not
interactive. Instead of just _displaying_ the grid interval, the new UI
allows you to modify the grid interval and the grid style right in the status
bar -- no dedicated dialog window is required anymore. Also the state of
placement locks is not only visible, but can be toggled right in the status
bar. Last but not least, there is a completely new notification system which
displays messages and ongoing operations in an expandable/collapsible popup
in the bottom right corner:

[.imageblock]
{{< imglink "statusbar" "statusbar.png" >}}

One Window is not Enough?
~~~~~~~~~~~~~~~~~~~~~~~~~

If you are working on a multi-monitor setup and now worry that a single window
is worse than the separate windows we had before -- of course this use-case
is covered as well. Although the new window replaces all the old windows,
we have implemented the ability to have *multiple instances* of that window
opened at the same time. So it is up to you if view schematic and board
side-by-side by splitting a single window, or if you just open schematic and
board in entirely separate windows.

State-Of-The-Art Library Management
-----------------------------------


Can't Wait to Give it a Try?
----------------------------
