---
date: 2025-05-22
title: Progress of LibrePCB 2.0
author: U. Bruhin
---

I'm making exciting progress towards the LibrePCB 2.0 milestone and gained a
lot of experience with our new UI toolkit https://slint.dev/[Slint] which I
think is worth to share.

The Big Problem
---------------

As initially mentioned in the blog post
link:{{< relref "blog/2024-10-17_roadmap_2.0/index.adoc" >}}[NGI0 Grant for LibrePCB 2.0],
I don't see our current UI toolkit Qt as a long-term solution anymore. It is
taking too much time to develop our UI and it brings a lot of annoying
limitations so we couldn't make LibrePCB as powerful as I want it to. But there
are not many other serious alternatives available. Slint looked interesting
at the first sight, but it was a high risk to go this route as it's still
a young project, especially for desktop applications. There's simply no proof
that it will work fine for LibrePCB.

The last ca. 5 months I worked hard on developing an entirely new LibrePCB UI
with Slint. After many long days and nights, I have now a better picture of
the capabilities of Slint than just after the evaluation, and luckily I'm now
quite confident we have taken the right decision.

The Bads
--------

Maturity
~~~~~~~~

With Qt, which has evolved the past 30 years(!), I was used to work with an
extremely reliable, mature and feature-rich piece of software. I didn't expect
this maturity from the much younger Slint project, and my expectations were
confirmed. Even during the relatively short time I'm using it, there popped
up many bugs, strange behavior and missing features. I observed even
regressions of features which worked fine in a previous release.

Beside reporting those bugs and feature requests to the Slint project (at least
the important ones), we will have to spend more time on testing before
creating new LibrePCB releases. Also we should enforce building LibrePCB with
a very specific (tested) version of Slint, which is the case as we integrated
Slint as a Git submodule. In addition, I had to spend quite some time to work
around missing features on my own.

For long term this problem should get smaller anyway with increasing maturity
of the Slint project.

Testing Framework
~~~~~~~~~~~~~~~~~


The Goods
---------

Painless Integration
~~~~~~~~~~~~~~~~~~~~

What surprised me a bit was the relatively easy integration of this quite
complex Rust library into our C++ code base. They provide a C++ API as a
CMake module which worked almost out of the box and on all of our supported
operating systems. Nice!

Slint DSL & Live Preview
~~~~~~~~~~~~~~~~~~~~~~~~

The best thing of Slint is for sure its domain-specific language. It is
incredible how much you can do with just a few lines of Slint code. And
despite being powerful, somehow it is still very simple. I think thanks to
this simplicity they are able to provide such a powerful live preview -- in
contrast to e.g. QML, it is not possible to build native (C++) UI components,
which would not work in a live preview.

Here's a short demonstration of the LibrePCB UI in the live preview, i.e.
the demonstrated functionality is implemented entirely in Slint and doesn't
involve any line of C++ code:

TODO

Support
~~~~~~~

I contacted Slint devs many times (questions, bug reports, feature requests)
and usually they were very quick and helpful. Some bugs were even fixed
immediately after reporting, and also my pull requests were reviewed and merged
within hours.



Challenges
----------

Coexistence with Qt
~~~~~~~~~~~~~~~~~~~

Slint supports different backends for interaction with the underlying system,
mainly for input handling and window drawing. For desktop systems these are
Qt, https://docs.rs/winit/latest/winit/[winit] and Linux KMS. With winit
there would be the ability of GPU-accelerated rendering, which could be
useful for performance reasons.

However, this means winit will run the main event loop which processes all I/O
events. Since our whole code base still uses Qt for non-UI things (including
timers, signal/slots etc.), it relies on the Qt event loop to be running and
taking care of I/O events. But we can't run both event loops, so the combination
of our Qt code base is not compatible with the winit backend.

Luckily Slint's Qt backend avoids that problem since Slint will run Qt's
event loop for us. Though this only works when both Slint and LibrePCB are
compiled & linked against the same Qt version, it turned out to work flawlessy
as the underlying https://docs.rs/qttypes/latest/qttypes/#finding-qt[qttype]
library simply use the system-provided Qt version, just as LibrePCB does.
Phuh...

Slint <-> C++ interaction
~~~~~~~~~~~~~~~~~~~~~~~~~

It took me a while to find concepts to properly "connect" the Slint UI with
our C++ backend. The functionality of Slint is very limited in this regard so
I had to be creative.
