---
date: 2025-08-30
title: Preview of LibrePCB 2.0 UI
author: U. Bruhin
---

I've made a lot of progress with the new user interface for LibrePCB 2.0 and
am very excited to share some insights how it will look and how it makes
LibrePCB better in many ways.

The Original Problem
--------------------

First, let's quickly look back how everything began. Since the early days of
LibrePCB around 2013, we are using Qt as the UI toolkit and the concept was
to implement every editor as a separate window (schematic editor, board editor,
library editor etc.):

// image

But with more and more features added, the UI got more and more crowded. Also
the paradigm of separate windows is often cumbersome to work with -- e.g.
having just one library and one project opened required to constantly switch
between 3 windows. Even a dual-monitor setup was not enough to work efficiently
with LibrePCB. So it was clear we need a completely new organization of windows
and editors. However, with the traditional approach that Qt follows, it is
really hard to pursue more modern UI paradigms, not to mention the effort and
the error-proneness it involves.

A Declarative Approach
----------------------

In the blog post
link:{{< relref "blog/2024-10-17_roadmap_2.0/index.adoc" >}}[NGI0 Grant for LibrePCB 2.0]
I listed a few possible solutions how to build a more moden user interface. The
most promising option was https://slint.dev/[Slint], a relatively new UI
toolkit (written in Rust) which uses a custom, declarative language to describe
the UI. Declarative means that relations and behavior can be described in the
language:

```
Window {
    Button {
        x: parent.width - self.width - 5px;
        y: 5px;
        text: @tr("Open Project");
    }
}
```

It may sound trivial to place a button in the top right edge of its parent,
but with a procedural approach like Qt this is not trivially doable. In many
cases, it requires to implement event handlers in C++ which update the
widgets position whenever the parent object's size or the widgets's own size
has changed. Writing such code is time-consuming and error-prone, while the
declarative approach of Slint is very quick, easy and safe. Now consider this
advantage for a large project like LibrePCB, that contains hundrets or even
thousands of UI elements -- here the declarative approach is really a
game-changer!

Coexistence with Qt
-------------------

Unfortunately, even with several months of full-time work, LibrePCB is too
big to be migrated to Slint by 100% at once -- to avoid delaying the next
release too much, we need to do the migration in steps. First all the main
windows & editors, and later the remaining dialogs and wizards. In addition,
we rely on Qt not only for the UI, but also the whole business logic is built
on top of Qt classes.

So the question is, can we mix Qt with Slint? How does that work? In the end,
LibrePCB only works if the main thread is running Qt's event loop. But Slint
only works when the main thread is running their event loop. This is needed
for the whole event processing. So we have a very bad conflict here :-/

Slint supports different backends for interaction with the underlying system,
mainly for input handling and window drawing. For desktop systems these are
Qt, https://docs.rs/winit/latest/winit/[winit] and Linux KMS. With winit
there would be the ability of GPU-accelerated rendering, which could be
useful for performance reasons.

However, this means winit will run the main event loop which processes all I/O
events. Since our whole code base still uses Qt for non-UI things (including
timers, signal/slots etc.), it relies on the Qt event loop to be running and
taking care of I/O events. But we can't run both event loops, so the combination
of our Qt code base is not compatible with the winit backend.

Luckily Slint's Qt backend avoids that problem since Slint will run Qt's
event loop for us. Though this only works when both Slint and LibrePCB are
compiled & linked against the same Qt version, it turned out to work flawlessy
as the underlying https://docs.rs/qttypes/latest/qttypes/#finding-qt[qttype]
library simply use the system-provided Qt version, just as LibrePCB does.
Phuh...

Slint <-> C++ interaction
~~~~~~~~~~~~~~~~~~~~~~~~~

It took me a while to find concepts to properly "connect" the Slint UI with
our C++ backend. The functionality of Slint is very limited in this regard so
I had to be creative.
