---
title: "Get Help"
icon: "fa-solid fa-circle-question"
weight: 10
url: /help
aliases: /discuss
---

== icon:message[] Forum

The best way for getting help or discussing improvement ideas is our
https://librepcb.discourse.group/[*discussion forum*]. Sign up and join the
conversation!

++++
<p class="text-center">
  <a class="btn btn-lg btn-dark" role="button"
     href="https://librepcb.discourse.group/">
    <i class="fa-brands fa-discourse"></i>
    LibrePCB Community
  </a>
</p>
++++

== icon:comments[] Chat
:matrix-space-url: https://matrix.to/#/#librepcb:matrix.org
:matrix-room-url: https://matrix.to/#/#librepcb-general:matrix.org

For quick conversations or to follow our internal discussions, join our
Matrix space {matrix-space-url}[#librepcb:matrix.org] (or join the main room
directly at {matrix-room-url}[#librepcb-general:matrix.org]):

++++
<p class="text-center">
  <a class="btn btn-lg btn-dark" role="button"
     href="https://matrix.to/#/#librepcb:matrix.org">
    [ LibrePCB Space ]
  </a>
</p>
++++

== icon:bug[] Issue Tracker

To report issues or for concrete feature requests,
https://github.com/LibrePCB/LibrePCB/issues[open an issue] in our issue
tracker. If you don't have a GitHub account, feel free to post your message
in the https://librepcb.discourse.group/[discussion forum] instead.

== icon:money-bill[] Paid Support

If you're interested in paid support or feature development service, please
link:{{< relref "about/contact/index.adoc" >}}[contact us].

== icon:envelope[] Contact

See link:{{< relref "about/contact/index.adoc" >}}[contact section].
